repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.2
      hooks:
        - id: seed-isort-config
    - repo: https://github.com/timothycrosley/isort
      rev: 18ad293fc9d1852776afe35015a932b68d26fb14
      hooks:
        - id: isort
          exclude: ^docs/

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
        - id: black
          exclude: ^docs/

    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          types:
            - python
          exclude: ^docs/
